version: '3'

services:
  nginx:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: nginx-container
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount file cấu hình Nginx
      - ./index.html:/root/index.html      # Mount file index.html
